### ISSUE TITLE
Updating tooling versions

### ISSUE THREAD

**Issue by vposham** [ThreeDotsLabs/watermill-benchmark#7]
Hello everyone, I think updating versions of all the tools used in here can help everyone. I can open a PR, if others are aligned.

Some notes on that - 
1. Kafka is always using Latest tag for docker image. 
2. Some changes were made to NATS as NATS Jetstream is now the default NATS implementation in watermills point of view. So it makes sense to upgrade to natsv2

**Comment by m110** [comment]
Hey @vposhamod, PRs are defenitely welcome! 👍

**Comment by AlexCuse** [comment]
Need to update for nats / jetstream v2 also.

**Comment by AlexCuse** [comment]
Happy to help w setup for NATS / Jetstream just noticed this table is out of date.

**Comment by m110** [comment]
All deps and benchmarks updated now. :)
